# Form implementation generated from reading ui file '.\\templates\\dlgGestionprop.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_tipoprop(object):
    def setupUi(self, dlg_tipoprop):
        dlg_tipoprop.setObjectName("dlg_tipoprop")
        dlg_tipoprop.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlg_tipoprop.resize(400, 300)
        dlg_tipoprop.setMinimumSize(QtCore.QSize(400, 300))
        dlg_tipoprop.setMaximumSize(QtCore.QSize(400, 300))
        dlg_tipoprop.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.label = QtWidgets.QLabel(parent=dlg_tipoprop)
        self.label.setGeometry(QtCore.QRect(160, 20, 91, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(60, 60))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\\\templates\\../img/inmoteis.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=dlg_tipoprop)
        self.frame.setGeometry(QtCore.QRect(60, 130, 291, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setObjectName("frame")
        self.lblTipoprop = QtWidgets.QLabel(parent=self.frame)
        self.lblTipoprop.setGeometry(QtCore.QRect(10, 30, 270, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTipoprop.sizePolicy().hasHeightForWidth())
        self.lblTipoprop.setSizePolicy(sizePolicy)
        self.lblTipoprop.setMinimumSize(QtCore.QSize(270, 20))
        self.lblTipoprop.setMaximumSize(QtCore.QSize(270, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblTipoprop.setFont(font)
        self.lblTipoprop.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lblTipoprop.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.lblTipoprop.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTipoprop.setObjectName("lblTipoprop")
        self.txtGestipoprop = QtWidgets.QLineEdit(parent=self.frame)
        self.txtGestipoprop.setGeometry(QtCore.QRect(70, 60, 150, 20))
        self.txtGestipoprop.setMinimumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setMaximumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setStyleSheet("")
        self.txtGestipoprop.setObjectName("txtGestipoprop")
        self.btnDeltipoprop = QtWidgets.QPushButton(parent=dlg_tipoprop)
        self.btnDeltipoprop.setGeometry(QtCore.QRect(240, 240, 80, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeltipoprop.sizePolicy().hasHeightForWidth())
        self.btnDeltipoprop.setSizePolicy(sizePolicy)
        self.btnDeltipoprop.setMinimumSize(QtCore.QSize(80, 25))
        self.btnDeltipoprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnDeltipoprop.setObjectName("btnDeltipoprop")
        self.btnAltatipoprop = QtWidgets.QPushButton(parent=dlg_tipoprop)
        self.btnAltatipoprop.setGeometry(QtCore.QRect(80, 240, 80, 25))
        self.btnAltatipoprop.setMinimumSize(QtCore.QSize(80, 25))
        self.btnAltatipoprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnAltatipoprop.setObjectName("btnAltatipoprop")

        self.retranslateUi(dlg_tipoprop)
        QtCore.QMetaObject.connectSlotsByName(dlg_tipoprop)

    def retranslateUi(self, dlg_tipoprop):
        _translate = QtCore.QCoreApplication.translate
        dlg_tipoprop.setWindowTitle(_translate("dlg_tipoprop", "Gestion Tipo Propiedades"))
        self.lblTipoprop.setText(_translate("dlg_tipoprop", "Introduzca tipo de propiedad a crear o eliminar"))
        self.btnDeltipoprop.setText(_translate("dlg_tipoprop", "Baja"))
        self.btnAltatipoprop.setText(_translate("dlg_tipoprop", "Alta"))
